name: CI

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: 12
      - run: npm install
      - run: node index.js
        env:
          NILE_CLIENT_GITHUB_TOKEN: ${{ secrets.NILE_CLIENT_GITHUB_TOKEN }}
